#!/bin/bash

# Start the application httpd instance

# Exit on any errors
set -e

# Get gear ip address.
gip=$(facter ipaddress)

echo "OPENSHIFT_ACTIVEMQ_AMQP=${OPENSHIFT_GEAR_DNS}|${gip}:${OPENSHIFT_ACTIVEMQ_AMQP_PROXY_PORT}"
echo "OPENSHIFT_ACTIVEMQ_OPENWIRE=${OPENSHIFT_GEAR_DNS}|${gip}:${OPENSHIFT_ACTIVEMQ_OPENWIRE_PROXY_PORT}"
